# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 914ce9c5018ef5c88bf61827feaaf4629efb39823910ff941c074b807169cfbe029bc1731a48044877300eafb9179e2153eea1200a3bf2a0a3730a3b51a48ee3

test:
  secret_key_base: b4d283da3070ce2f28c2244678cc82a01f76fc76abf99d94e0054d00a9cd07a1671e7f1c8f19d364213fe133acc064635ffe705de21a3f32d868ce090a3fd778

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
